# Generated by Django 5.0.2 on 2024-02-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_Study', models.TextField()),
                ('date_added', models.DateField()),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Study',
        ),
    ]
