# Generated by Django 5.0.2 on 2024-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_progress_delete_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='content',
            new_name='catatan',
        ),
        migrations.AlterField(
            model_name='progress',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
